djangoprodject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lib/', include('lib.urls')),
    path('', RedirectView.as_view(url='lib/', permanent=True)),
]

lib/urls.py
from django.urls import path
from . import views
app_name="lib"

urlpatterns = [
    path('', views.index, name="index"),
    path('books/', views.book_list, name="book_list"),
    path('genres/', views.genre_list, name="genre_list"),
    path('authors/', views.author_list, name="author_list"),
    path('book/<int:pk>/', views.book_detail, name="book_detail"),
    path('genre/<int:pk>/', views.genre_detail, name="genre_detail"),
    path('author/<int:pk>/', views.author_detail, name="author_detail"),
#http://127.0.0.1:8000/lib/api/books/all/
    path('api/books/all', views.BookListAPIView.as_view(), name="api_book_list"),
#http://127.0.0.1:8000/lib/api/author/1/
    path('api/author/<int:pk>', views.AuthorDetailAPIView.as_view(), name="api_author_list"),
]

lib/models.py
from django.db import models
from django.urls import reverse

class Genre(models.Model):
    name=models.CharField(max_length=20)

    def __str__(self):
        return self.name
    def get_absolut_url(self):
        return reverse('lib:genre_detail', args=(self.id,))


    class Meta:
        ordering=["name"]
class Author(models.Model):
    first=models.CharField(max_length=50)
    last=models.CharField(max_length=50)
    year=models.IntegerField(default=0)
    img=models.URLField(blank=True, null=True)
    def __str__(self):
        return self.first+' '+self.last
    def get_absolute_url(self):
        return reverse('lib:author_detail', args=(self.id,))

    def get_genres(self):
        genres = []
        for book in self.book_set.all():
            for genre in book.genre.all():
                genres.append(genre)
        return list(set(genres))

    class Meta:
        ordering=["last"]
class Book(models.Model):
    title=models.CharField(max_length=50)
    author=models.ForeignKey(Author, on_delete=models.SET_NULL, null=True)
    summary=models.TextField(blank=True, null=True)
    genre=models.ManyToManyField(Genre)
    img = models.URLField(blank=True, null=True)
    def __str__(self):
        return f'"{self.title}"'
    def genres_str(self):
        return ', '.join(genre.name for genre in self.genre.all())
    def get_absolute_url(self):
        return reverse('lib:book_detail', args=(self.id,))

    class Meta:
        ordering=["title"]

class BookInstance(models.Model):
    book=models.ForeignKey(Book, on_delete=models.SET_NULL, null=True)
    LOAN_STATUSES=(
        ('a', 'Available'),
        ('r', 'Reserved'),
        ('o', 'On Loan'),
    )
    status=models.CharField(max_length=1, choices=LOAN_STATUSES, default='a')
    due_back=models.DateField(null=True, blank=True)
    def __str__(self):
        return f'{self.book} id={self.id} status={self.status}'


# Create your models here.

lib/views.py
from django.shortcuts import render
from django.http import HttpResponse
from rest_framework import generics

from .models import *
from .serializers import *
def look_ups():
    #print('#1')
    author1=Author.objects.get(first__iexact='jane')
    #print(author1)
def index(request):
    look_ups()
    n_books=Book.objects.all().count()
    n_authors = Author.objects.all().count()
    n_genres = Genre.objects.all().count()
    n_av_instances=BookInstance.objects.filter(status__exact='a').count()
    context={
        'n_books': n_books,
        'n_authors': n_authors,
        'n_genres': n_genres,
        'n_av_instances': n_av_instances,
    }
    #return HttpResponse('<h1>Local Library</h1>')
    return render(request, 'lib/index.html', context)
def book_list(request):
    context={
        'books': Book.objects.all(),
    }
    return render(request, 'lib/book_list.html', context)
def genre_list(request):
    context={
        'genres': Genre.objects.all(),
    }
    return render(request, 'lib/genre_list.html', context)

def author_list(request):
    context={
        'authors': Author.objects.all(),
    }
    return render(request, 'lib/author_list.html', context)
def book_detail(request, pk):
    context={
        'book': Book.objects.get(pk=pk),
    }
    return render(request, 'lib/book_detail.html', context)
def genre_detail(request, pk):
    context={
        'genre': Genre.objects.get(pk=pk),
    }
    return render(request, 'lib/genre_detail.html', context)
def author_detail(request, pk):
    context={
        'author': Author.objects.get(id__exact=pk),
    }
    #print(context['author'].get_genres())
    return render(request, 'lib/author_detail.html', context)

class BookListAPIView(generics.ListAPIView):
    queryset = Book.objects.all()
    serializer_class = BookSerializer1

class AuthorDetailAPIView(generics.RetrieveAPIView):
    queryset = Author.objects.all()
    serializer_class = AuthorSerializer1

lib/templates/lib/author_detail.html
{% extends 'lib/base.html'  %}
{% block title %}{{ author }}{% endblock %}

{% block content %}
<h1>{{ author }}</h1>
<div class="row">
    <div class="col-2">
        <img src="{{ author.img }}" class="img-fluid">
    </div>
    <div class="col-2">
        <h4>genres:</h4>
        {% for genre in author.get_genres %}
        <small>
            <a href="{{ genre.get_absolut_url }}"><p>{{ genre }}</p></a>
        </small><br>
        {% endfor %}
    </div>
    <div class="col-8">
        {% for book in author.book_set.all %}
        <div class="row mb-4">
           <div class="col-2">
                <img src="{{ book.img }}" class="img-fluid">
           </div>
            <div class="col-10">
                <a href="{{ book.get_absolute_url }}">
                    <p>{{ book }}</p>
                </a>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

lib/templates/lib/author_list.html
{% extends 'lib/base.html'  %}
{% load static %}

{% block title %}All Authors{% endblock %}

{% block content %}
<h1>All Authors ({{ authors|length }})</h1>

{% for author in authors %}
<a href="{{ author.get_absolute_url }}" class="text-decoration-none">{{ author }} (books: {{ author.book_set.all|length }})</a>
<br>
{% endfor %}

{% endblock %}

lib/templates/lib/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'lib/css/custom.css' %}">
    <link rel="icon" type="image/png" href="{% static 'lib/img/icon.png' %}">
</head>
<body>
    <div class="container">
        <a href="{% url 'lib:index' %}">
            <img src="{% static 'lib/img/icon.png' %}" width="35">
        </a>
        {% block content %}{% endblock %}
    {% include 'lib/footer.html' %}
    </div>
</body>
</html>

lib/templates/lib/book_detail.html
{% extends 'lib/base.html'  %}
{% block title %}{{ book }} by {{ book.author }}{% endblock %}

{% block content %}
<h1>{{ book }} by
    <a href="{{ book.author.get_absolute_url }}" class="text-decoration-none">{{ book.author }}</a>
</h1>
<div class="row">
<div class="col-2">
    <img src="{{ book.img }}" class="img-fluid">
    <hr>
    <h6>Instances of {{ book }}:</h6>
    {% for fi in book.bookinstance_set.all %}
    <p>id: {{ fi.id }} status: "{{ fi.get_status_display }}"
    {% if fi.status == 'o' %}
        (will be returned at {{ fi.due_back|date:'d.m.Y' }})
    {% endif %}
    </p>
    {% endfor %}
</div>
<div class="col-2">
    <h4>genres:</h4>
    {% for genre in book.genre.all %}
    <a href="{{ genre.get_absolut_url }}"> <p>{{ genre }}</p></a>
    {% endfor %}
</div>
<div class="col-8">
    <h4>Summary:</h4>
    <p>{{ book.summary }}</p>
</div>
</div>
{% endblock %}

lib/templates/lib/book_list.html
{% extends 'lib/base.html'  %}
{% load static %}

{% block title %}All Books{% endblock %}

{% block content %}
<h1>All Books ({{ books|length }})</h1>
<div class="row">
    {% for book in books %}
    <div class="col-3">
        <img src="{{ book.img }}" width="200" height="300">
        <h4><a href="{{ book.get_absolute_url }}">{{ book }}</a></h4>
        <h6><a href="{{ book.author.get_absolute_url }}">{{ book.author }}</a></h6>
    </div>
    {% endfor %}
</div>

{% endblock %}

lib/templates/lib/footer.html
<footer class="page-footer font-small special-color-dark pt-4">

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2020 Copyright:
    <a href="http://127.0.0.1:8000/lib/"> Library.vele.com</a>
  </div>
  <!-- Copyright -->

</footer>

lib/templates/lib/genre_detail.html
{% extends 'lib/base.html'  %}
{% block title %}{{ genre }}{% endblock %}

{% block content %}
<h1>Books by genre: {{ genre }}({{ genre.book_set.all|length }})</h1>

<div class="row">
    {% for book in genre.book_set.all %}
    <div class="col-3">
        <img src="{{ book.img }}" width="200" height="300">
        <h4><a href="{{ book.get_absolute_url }}">{{ book }}</a></h4>
        <h6><a href="{{ book.author.get_absolute_url }}">{{ book.author }}</a></h6>
    </div>
    {% endfor %}
</div>
{% endblock %}

lib/templates/lib/genre_list.html
{% extends 'lib/base.html'  %}
{% load static %}

{% block title %}All Genres{% endblock %}

{% block content %}
<h1>All Genres ({{ genres|length }})</h1>

{% for genre in genres %}
<a href="{{ genre.get_absolut_url }}" class="text-decoration-none">{{ genre }}</a>
<br>
{% endfor %}

{% endblock %}

lib/templates/lib/index.html
{% extends 'lib/base.html'  %}
{% load static %}

{% block title %}Library{% endblock %}

{% block content %}
<h1>Library</h1>
<div class="row">
    <div class="col-3">
        <a href="{% url 'lib:book_list' %}">Books: {{ n_books }}</a>
    </div>
    <div class="col-3">
        <a href="{% url 'lib:author_list' %}">Authors: {{ n_authors }}</a>
    </div>
    <div class="col-3">
        <a href="{% url 'lib:genre_list' %}" >Genres: {{ n_genres }}</a>
    </div>
    <div class="col-3">
        <a href="#">Available Instances: {{ n_av_instances }}</a>
    </div>
</div>
<div class="row justify-content-center">
    <div class="col-6">
        <img class="imj-fluid" src="{% static 'lib/img/book.jpg' %}" width="500">
    </div>
</div>
{% endblock %}